name: Ombulabs Blog
description: The Ombulabs team blog
meta_description: "Ombulabs Blog, The Ombulabs team blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://blog.ombulabs.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'Ombulabs'

exclude: ['vendor']
