name: Ombulabs Blog
description: The Ombulabs team blog
meta_description: "Ombulabs Blog, The Ombulabs team blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /blog
domain_name: 'http://www.ombulabs.com'
google_analytics: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
permalink: pretty

# Details for the RSS feed generator
url:            'blog url'
author:         'Ombulabs'

exclude: ['vendor']
