name: Ombulabs Blog
description: The Lean Software Boutique
meta_description: "OmbuLabs Blog, The Lean Software Boutique's blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /blog
domain_name: 'http://www.ombulabs.com'
permalink: none
category_dir: 'tags'
excerpt_separator: "<!--more-->"

# Details for the RSS feed generator
url:            'blog url'
author:         'Ombulabs'

exclude: ['vendor']

authors:
  etagwerker:
    display_name: Ernesto Tagwerker
    gravatar: 9299203e7e9b9ae35e39eb66f3155f15
    email: ernesto@ombulabs.com
    twitter: etagwerker
    github: etagwerker
  mauro-oto:
    display_name: Mauro Otonelli
    gravatar: 350875eb8fce8553e12040c5a1f5d5d0
    email: mauro@ombulabs.com
    twitter: mauro_oto
    github: mauro-oto
