name: Ombulabs Blog
description: The Ombulabs team blog
meta_description: "Ombulabs Blog, The Ombulabs team blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /blog
domain_name: 'http://www.ombulabs.com'
google_analytics: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
permalink: pretty

# Details for the RSS feed generator
url:            'blog url'
author:         'Ombulabs'

exclude: ['vendor']

authors:
  etagwerker:
    display_name: Ernesto Tagwerker
    gravatar: 9299203e7e9b9ae35e39eb66f3155f15
    email: ernesto@ombulabs.com
    twitter: etagwerker
    github: etagwerker
  mauro-oto:
    display_name: Mauro Otonelli
    gravatar: 
    email: mauro@ombulabs.com
    twitter: mauro_oto
    github: mauro-oto
